export enum QueryTypes {
  SELECT = 'SELECT',
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  BULKUPDATE = 'BULKUPDATE',
  BULKDELETE = 'BULKDELETE',
  DELETE = 'DELETE',
  UPSERT = 'UPSERT',
  VERSION = 'VERSION',
  SHOWTABLES = 'SHOWTABLES',
  SHOWINDEXES = 'SHOWINDEXES',
  DESCRIBE = 'DESCRIBE',
  RAW = 'RAW',
  FOREIGNKEYS = 'FOREIGNKEYS',
  SHOWCONSTRAINTS = 'SHOWCONSTRAINTS',
}

export const STATUS_CODES = {
  SUCCESS: 200,
  UNAUTHORISED: 401,
  BAD_REQUEST: 400,
  METHOD_NOT_FOUND: 405,
  SERVER_ERROR: 500,
  NOT_FOUND: 404,
  UN_PROCESSABLE: 422,
  NO_CONTENT: 204,
  CREATED: 201,
  SPECIAL_STATUS: 600,
  FORBIDDEN: 403,
  CONFLICT: 409,
};

export const RESPONSE_MESSAGE = {
  SERVER_ERROR: 'Internal Server Error!',
  AUTH_FAILURE: 'Bad Token error',
  CUSTOM_TOKEN_GENERATION_FAILED: 'Error generating custom token from Firebase',
};

export const ERROR_CODES = {
  NO_ACTIVE_SUBSCRIPTION_PLAN: 'NO_ACTIVE_SUBSCRIPTION_PLAN',
  TRANSACTION_ROLLED_BACK: 'TRANSACTION_ROLLED_BACK',
  OTP_SEND_FAILURE: 'OTP_SEND_FAILURE',
  EMAIL_SEND_FAILURE: 'EMAIL_SEND_FAILURE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DATA_NOT_FOUND: 'DATA NOT FOUND',
  AUTH_FAILURE: 'AUTH_FAILURE',
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  OTP_MISMATCH: 'OTP_MISMATCH',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_REQUIRED_ERROR: 'EMAIL_REQUIRED_ERROR',
  PHONE_REQUIRED_ERROR: 'PHONE_REQUIRED_ERROR',
  FULLNAME_REQUIRED_ERROR: 'FIRSTNAME_REQUIRED_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  NOTHING_TO_UPDATE: 'NOTHING_TO_UPDATE',
  OPERATION_FAILED: 'OPERATION_FAILED',
  RESOURCE_NOT_UPDATED: 'RESOURCE_NOT_UPDATED',
  CUSTOM_TOKEN_GENERATION_FAILED: 'CUSTOM_TOKEN_GENERATION_FAILED',
};

export const BOOLEAN = {
  TRUE: true,
  FALSE: false,
};

export const HTTP_METHODS = {
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  DELETE: 'DELETE',
  GET: 'GET',
};

export const BASE_ENDPOINT = 'api/v1';
export const APPLICATION_NAME = 'Application';

export const STATUS = {
  ACTIVE: 'ACTIVE',
  DELETE: 'DELETE',
};

export const HOURS_CONSTANTS = {
  TWENTY_FOUR: 24,
  FORTY_EIGHT: 48,
};

export const REQUEST_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  DELETED_BY_USER: 'DELETED_BY_USER',
};

export const USER = 'USER';
export const HEALTH_ENDPOINT = '/healthCheck';
export const SERVER_STATUS = {
  UP: 'UP',
  DOWN: 'DOWN',
};
export const CATEGORY_ENDPOINT = '/category';
export const CATEGORY_ID_ENDPOINT = '/:category_id';
