export const PROJECT_AND_UNIT_ERR = {
  NOT_FOUND: {
    CODE: 'PROJECT_OR_UNIT_NOT_FOUND',
    MESSAGE: 'PROJECT_OR_UNIT_NOT_FOUND',
  },
  PROJECT_STATUS_INVALID: {
    CODE: 'PROJECT_STATUS_INVALID',
    MESSAGE: 'PROJECT_STATUS_INVALID',
  },
  NOT_FOUND_OR_STATUS_INVALID: {
    CODE: 'PROJECT_NOT_FOUND_OR_STATUS_INVALID',
    MESSAGE: 'PROJECT_NOT_FOUND_OR_STATUS_INVALID',
  },
};
