export const DEMAND_TYPE = {
  CATAMARAN: 'CATAMARAN',
  MAINTENANCE_PAYMENT: 'MAINTENANCE_PAYMENT',
  NON_BUDGETED_DEMAND: 'NON_BUDGETED_DEMAND',
  OTHER: 'OTHER',
};
export const DEMAND_PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  COMPLETED: 'COMPLETED',
  OVERDUE: 'OVERDUE',
};

export const TRANSACTION_PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};
export const PAYMENT_MODE = { OFFLINE: 'OFFLINE', ONLINE: 'ONLINE' };
export const DEMAND_ENDPOINT = '/demand';
export const DEMAND_ID_ENDPOINT = '/:demand_id';
export const TRANSACTION_ENDPOINT = '/transaction';
export const GENERATE_HASH_ENDPOINT = '/generate_hash';
