export const SITE_VISIT_REQUEST_ENDPOINT = '/site_visit_requests';
export const SITE_VISIT_REQUEST_ERR = {
  ALREADY_EXISTS: {
    CODE: 'SITE_VISIT_REQUEST_EXISTS',
    MESSAGE: 'SITE_VISIT_REQUEST_EXISTS',
  },
  BAD_REQUEST: {
    CODE: 'INVALID_REQUEST',
    MESSAGE: 'INVALID_REQUEST',
  },
};
