#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format || (echo 'Prettier Check Failed. Running npm run format...' && npm run format)

# Check ESLint Standards
npm run lint || (echo 'ESLint Check Failed. Running npm run lint-fix...' && npm run lint-fix)

# Check tsconfig standards
npm run check-types || (echo 'Failed Type check' && exit 1)

# If everything passes... Now we can commit
echo 'Everything is good. Building...'

npm run build || (echo 'Build failed' && exit 1)

# If everything passes... Now we can commit
echo 'Passed checks can commit now'